// <auto-generated />
using Gap.Domain.Customer.Model;
using Gap.Domain.Customer.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Gap.Domain.Customer.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20181014060723_CustomerInsurance")]
    partial class CustomerInsurance
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("Relational:Sequence:Customer.customer_seq", "'customer_seq', 'Customer', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gap.Domain.Customer.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:HiLoSequenceName", "customer_seq")
                        .HasAnnotation("SqlServer:HiLoSequenceSchema", "Customer")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Email");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Customer","Customer");
                });

            modelBuilder.Entity("Gap.Domain.Customer.Model.CustomerInsurance", b =>
                {
                    b.Property<int>("InsuranceId");

                    b.Property<int>("CustomerId");

                    b.Property<int>("Status");

                    b.HasKey("InsuranceId", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerInsurance","Customer");
                });

            modelBuilder.Entity("Gap.Domain.Customer.Model.CustomerInsurance", b =>
                {
                    b.HasOne("Gap.Domain.Customer.Model.Customer", "Customer")
                        .WithMany("Insurances")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
